language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install .[test]
script:
  - pytest --cov-config=.coveragerc --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash) -v
